include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "example/**"
    - "**/*.entity_mapper.dart"  # Exclude generated files too
    - "**/*_model.dart"
    - "test/**"
