name: entity_mapper
description: Clean Architecture entity mapping made simple
version: 0.1.0
homepage: https://github.com/r2am9d/entity_mapper
repository: https://github.com/r2am9d/entity_mapper
documentation: https://github.com/r2am9d/entity_mapper#readme
topics:
  - clean-architecture
  - dart-mappable
  - entity-mapping
  - code-generation
  - flutter
  - dart

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  analyzer: ^7.7.1
  build: ^3.0.0
  flutter:
    sdk: flutter
  meta: ^1.15.0
  source_gen: ^3.1.0

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
